services:
    rabbitmq:
        image: rabbitmq:3-alpine
        volumes:
            - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:r
        ports:
            - "15672:15672"
            - "5672:5672"
